# Generated by Django 2.0 on 2019-04-05 02:01

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_label', models.CharField(max_length=50)),
                ('Content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('alter_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Article',
            },
        ),
    ]
